[tinySolarNode]
extends = stm32_base
board = E77_xxxM22S
board_upload.maximum_size = 229376 ; 32kb for FS
build_flags = ${stm32_base.build_flags}
  -D RADIO_CLASS=CustomSTM32WLx
  -D WRAPPER_CLASS=CustomSTM32WLxWrapper
  -D SPI_INTERFACES_COUNT=0
  -D RX_BOOSTED_GAIN=true
;  -D STM32WL_TCXO_VOLTAGE=1.6 ; defaults to 0 if undef
;  -D LORA_TX_POWER=14 ; Defaults to 22 for HP, 14 is for LP version
  -I variants/tinySolarNode
  -Wl,-Map=output.map
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
build_src_filter = ${stm32_base.build_src_filter}
  +<../variants/tinySolarNode>

[env:tinySolarNode_repeater]
extends = tinySolarNode
build_flags = ${tinySolarNode.build_flags}
  -D ADVERT_NAME='"tinySolarNode Repeater"'
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=100
build_src_filter = ${tinySolarNode.build_src_filter}
  +<../examples/simple_repeater/*.cpp>

[env:tinySolarNode_sensor]
extends = tinySolarNode
build_flags = ${tinySolarNode.build_flags}
  -D ADVERT_NAME='"tinySolarNode Sensor"'
  -D ADMIN_PASSWORD='"password"'
build_src_filter = ${tinySolarNode.build_src_filter}
  +<../examples/simple_sensor>

;[env:tinySolarNode_companion_radio_usb]
;extends = tinySolarNode
;build_flags = ${tinySolarNode.build_flags}
;  -D FORMAT_FS=true
;  -D MAX_CONTACTS=100
;  -D MAX_GROUP_CHANNELS=8
;build_src_filter = ${tinySolarNode.build_src_filter}
;  +<../examples/companion_radio/*.cpp>
;lib_deps = ${tinySolarNode.lib_deps}
;  densaugeo/base64 @ ~1.4.0
