[SolarNodeL431]
extends = stm32_base
board = stm32l431cct6
board_upload.maximum_size = 229376 ; 32kb for FS
build_flags = ${stm32_base.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D SPI_INTERFACES_COUNT=2
  -fsingle-precision-constant
  -Wall
  -Wextra
  -Wdouble-promotion
  -I variants/SolarNodeL431
  -Wl,-Map=output.map
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
build_src_filter = ${stm32_base.build_src_filter}
  +<../variants/SolarNodeL431>

[env:SolarNodeL431_repeater]
extends = SolarNodeL431
build_flags = ${SolarNodeL431.build_flags}
  -D ADVERT_NAME='"SolarNodeL431 Repeater"'
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=100
build_src_filter = ${SolarNodeL431.build_src_filter}
  +<../examples/simple_repeater/*.cpp>

[env:SolarNodeL431_sensor]
extends = SolarNodeL431
build_flags = ${SolarNodeL431.build_flags}
  -D ADVERT_NAME='"SolarNodeL431 Sensor"'
  -D ADMIN_PASSWORD='"password"'
build_src_filter = ${SolarNodeL431.build_src_filter}
  +<../examples/simple_sensor>

;
 ; -mfloat-abi=hard
 ; -mfpu=fpv4-sp-d16
 ; -mcpu=cortex-m4
;[env:SolarNodeL431_companion_radio_usb]
;extends = SolarNodeL431
;build_flags = ${SolarNodeL431.build_flags}
;  -D FORMAT_FS=true
;  -D MAX_CONTACTS=100
;  -D MAX_GROUP_CHANNELS=8
;build_src_filter = ${SolarNodeL431.build_src_filter}
;  +<../examples/companion_radio/*.cpp>
;lib_deps = ${SolarNodeL431.lib_deps}
;  densaugeo/base64 @ ~1.4.0
