[SolarNodeL431]
extends = stm32_base
board = stm32l431cct6
;board_upload.maximum_size = 229376 ; 32kb for FS
build_flags = ${stm32_base.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D SPI_INTERFACES_COUNT=2
  -D LORA_FREQ=864.281
  -D LORA_BW=62.5
  -D LORA_SF=8
  -D LORA_CR=6
;  -D LORA_TX_POWER=1
  -D LORA_TX_POWER=19
  -D ADMIN_PASSWORD='"password"'
  -fsingle-precision-constant
  -Wall
  -Wextra
  -Wdouble-promotion
  -I variants/SolarNodeL431
  -Wl,-Map=output.map
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
  -g
  
build_src_filter = ${stm32_base.build_src_filter}
  +<../variants/SolarNodeL431>
  +<../lib/STM32-W25Q-QSPI>
  +<../src/helpers/w25qFS>

[env:SolarNodeL431_repeater]
extends = SolarNodeL431
build_flags = ${SolarNodeL431.build_flags}
  -D ADVERT_NAME='"SolarNodeL431 Repeater"'
  -D MAX_NEIGHBOURS=100
  -D SERIAL_UART_INSTANCE=2
; -D FORMAT_FS=true
;  -D MESH_PACKET_LOGGING=1
build_src_filter = ${SolarNodeL431.build_src_filter}
  +<../examples/simple_repeater/*.cpp>

[env:SolarNodeL431_sensor]
extends = SolarNodeL431
build_flags = ${SolarNodeL431.build_flags}
  -D ADVERT_NAME='"SolarNodeL431 Sensor"'
build_src_filter = ${SolarNodeL431.build_src_filter}
  +<../examples/simple_sensor>
  
[env:SolarNodeL431_companion_radio_usb]
extends = SolarNodeL431
build_flags = ${SolarNodeL431.build_flags}
;  -D FORMAT_FS=true
  -D MAX_CONTACTS=200
  -D MAX_GROUP_CHANNELS=20
  -D SERIAL_UART_INSTANCE=1
build_src_filter = ${SolarNodeL431.build_src_filter}
  +<../examples/companion_radio/*.cpp>
lib_deps = ${SolarNodeL431.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:SolarNodeL431_room_server]
extends = SolarNodeL431
build_flags =
  ${SolarNodeL431.build_flags}
  -D ADVERT_NAME='"SolarNodeL431 Room"'
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
  -D MAX_UNSYNCED_POSTS=128
build_src_filter = ${SolarNodeL431.build_src_filter}
  +<../examples/simple_room_server>
lib_deps = ${SolarNodeL431.lib_deps}